[workspace]
members = ["st_wba_ble_sys", "st_wba_ble"]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
  'cfg(nightly)',
  'cfg(arm_llsc)',
  'cfg(has_atomic_load_store)'
] }
