name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # If you chose Option B (no symlink), uncomment the env below:
    # env:
    #   STM32CUBEWBA_DIR: ${{ github.workspace }}/external/STM32CubeWBA

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust (stable) + Cortex-M target
        uses: dtolnay/rust-toolchain@stable
        with:
          # Pick the one you actually use:
          targets: thumbv8m.main-none-eabihf

      - name: Install system deps (ARM GCC + clang)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi clang pkg-config

      - name: Build workspace
        run: |
          cargo build --workspace --locked

